project_id = "cywngfflmpdpuqaigsjc"

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-send-message]
verify_jwt = true

[functions.telegram-broadcast]
verify_jwt = true

[functions.telegram-bot-setup]
verify_jwt = true